### PR TITLE
Automate pprof/Go installation on Linux

### PR DESCRIPTION
**Pull request by wlandau**
# Summary

This PR implements `install_go()`, which installs Go (and by extension, `pprof`) if on Linux and links to graphical installers on Mac and Windows. The PR also updates the installation and configuration instructions. I think this is as far as we can get with #11. cc @krlmlr.

# Related GitHub issues and pull requests

- Ref: #11

# Checklist

- [x] I understand and agree to `proffer`'s [code of conduct](https://github.com/r-prof/proffer/blob/master/CODE_OF_CONDUCT.md).
- [x] I have listed any substantial changes in the [development news](https://github.com/r-prof/proffer/blob/master/NEWS.md).
- [x] I have added [`testthat`](https://github.com/r-lib/testthat) unit tests to [`tests/testthat`](https://github.com/r-prof/proffer/tree/master/tests/testthat) for any new functionality. Feel free to use `skip("interactive only")` for any tests that cannot be fully automated.
- [x] This pull request is not a [draft](https://github.blog/2019-02-14-introducing-draft-pull-requests).

### CODE REVIEW

**Review by krlmlr — COMMENTED** [review]
Do we still need Go if we have a working installation of `pprof`?

**Comment by wlandau** [comment]
I don't know, maybe you could remove Go after installing `pprof`, I have not tried. But what I learned from  is that installing Go is probably the most convenient way to install `pprof`, so I expect most people to have Go anyway.

**Comment by wlandau** [comment]
Might also be nice to be able to `go get google.com/google/pprof` if the need arises. Are you thinking `pprof_sitrep()` should only focus on `pprof` and Graphviz and that we do not need `PROFFER_GO_BIN`?

**Comment by wlandau** [comment]
Merging because some folks at the [Chicago R Collab](https://chircollab.github.io/) may find this useful.

**Pull request merged**
