### PR TITLE
Implement pprof_sitrep()

### PR DESCRIPTION
**Pull request by wlandau**
# Summary

cc @krlmlr 

`pprof_sitrep()` checks the non-R dependencies and environment variables and gives a detailed report of what is installed/configured and what is missing.

``` r
proffer::pprof_sitrep()
#> ● Call test_pprof() to test installation.
#> ✓ pprof path /Users/CENSORED/go/bin/pprof
#> ✓ PROFFER_PPROF_PATH path /Users/CENSORED/go/bin/pprof
#> ✓ pprof_path env variable omitted
#> ✓ pprof system path /Users/CENSORED/go/bin/pprof
#> ✓ Go path /Users/CENSORED/go
#> ✓ Go binary path /usr/local/bin/go
#> ✓ PROFFER_GO_PATH path /usr/local/bin/go
#> ✓ Go binary system path /usr/local/bin/go
#> ✓ Graphviz path /usr/local/bin/dot
#> ✓ PROFFER_GRAPHVIZ_PATH /usr/local/bin/dot
#> ✓ Graphviz system path /usr/local/bin/dot
```

The PR also refactors `pprof_path()` using functional programming.

<sup>Created on 2020-02-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

# Related GitHub issues and pull requests

- Ref: #17

# Checklist

- [x] I understand and agree to `proffer`'s [code of conduct](https://github.com/r-prof/proffer/blob/master/CODE_OF_CONDUCT.md).
- [x] I have listed any substantial changes in the [development news](https://github.com/r-prof/proffer/blob/master/NEWS.md).
- [x] I have added [`testthat`](https://github.com/r-lib/testthat) unit tests to [`tests/testthat`](https://github.com/r-prof/proffer/tree/master/tests/testthat) for any new functionality. Feel free to use `skip("interactive only")` for any tests that cannot be fully automated.
- [x] This pull request is not a [draft](https://github.blog/2019-02-14-introducing-draft-pull-requests).

### CODE REVIEW

**Review by krlmlr — COMMENTED** [review]
Thanks, this is a great step forward. I'd like to see a correspondence between the lookup logic and the sitrep.

I have drafted cc5e77d0 (incomplete). The new `lookup.R` contains complex logic for both lookup and sitrep, the original `path.R` and `sitrep.R` contain simple logic and the messages. This needs a bit more work. What do you think?

**Comment by wlandau** [comment]
I see your point about self-consistency, but in this case I would actually prefer to run all sitrep checks independently. It is nice to have explicit confirmation on the status of environment variables, even when they are not being used at the moment. For users unfamiliar with environment variables, it will give them more information about how to manually configure the dependencies in case they need to do so at some point. In the past, I have had problems with older versions of `pprof` on machines where I was not an admin, and I would have appreciated the extra verbosity and guaranteed feedback.

Also, I am starting to question the name `pprof_sitrep()`. The word "sitrep" fits, but I am starting to think something like `pprof_checks()` or `check_pprof()` might be clearer.

**Comment by wlandau** [comment]
I do think we should still distinguish between unmet requirements and mild suggestions, and I think `cli_alert_danger()` vs `cli_alert_info()` accomplishes this already.

**Comment by wlandau** [comment]
Perhaps we could reorder the output to distinguish between bottom-line system checks and optional environment variables?

```r
proffer::pprof_sitrep()
#> ● Call test_pprof() to test installation.
#> ── Requirements ─────────────────────────────────
#> ✓ pprof /Users/CENSORED/go/bin/pprof
#> ✓ Go /Users/CENSORED/go
#> ✓ Graphviz /usr/local/bin/dot
#> ── Custom ───────────────────────────────────────
#> ✓ PROFFER_PPROF_PATH /Users/CENSORED/go/bin/pprof
#> ✓ PROFFER_GO_PATH /usr/local/bin/go
#> ✓ PROFFER_GRAPHVIZ_PATH /usr/local/bin/dot
#> ── System ───────────────────────────────────────
#> ✓ pprof /Users/CENSORED/go/bin/pprof
#> ✓ Go binary /usr/local/bin/go
#> ✓ Graphviz /usr/local/bin/dot
#> ── Deprecated ───────────────────────────────────
#> ✓ pprof_path env variable omitted
```

**Comment by wlandau** [comment]
Just implemented https://github.com/r-prof/proffer/pull/19#issuecomment-593207912 in b530c5ef0a29b24941c612c910995ae08f01a0e5. I feel the output is clear on what is required and what is configurable, so we hopefully don't need to follow the logic of `pprof_path()`.

``` r
proffer::pprof_sitrep()
#> ● Call test_pprof() to test installation.
#> 
#> ── Requirements ─────────────────────────────────────────────────
#> ✓ pprof /home/landau/go/bin/pprof
#> ✓ Go folder /home/landau/go
#> ✓ Go binary /usr/bin/go
#> ✓ Graphviz /usr/bin/dot
#> 
#> ── Custom ───────────────────────────────────────────────────────
#> ✓ PROFFER_PPROF_PATH /home/landau/go/bin/pprof
#> ℹ PROFFER_GO_PATH missing
#> ● Run usethis::edit_r_environ() to edit .Renviron file.
#> ● PROFFER_GO_PATH=/usr/bin/go
#> ℹ PROFFER_GRAPHVIZ_PATH missing
#> ● Run usethis::edit_r_environ() to edit .Renviron file.
#> ● PROFFER_GRAPHVIZ_PATH=/usr/bin/dot
#> 
#> ── System ───────────────────────────────────────────────────────
#> ✓ pprof system path /home/landau/go/bin/pprof
#> ✓ Go binary system path /usr/bin/go
#> ✓ Graphviz system path /usr/bin/dot
#> 
#> ── Deprecated ───────────────────────────────────────────────────
#> ℹ pprof_path /home/landau/go/bin/pprof
#> ● pprof_path is deprecated. Use PROFFER_PPROF_PATH instead.
```

<sup>Created on 2020-03-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by krlmlr** [comment]
There's also `usethis:git_sitrep()`, `usethis:proj_sitrep()` and `cli::cli_sitrep()` with similar purposes.

Can we use markup to highlight important information in the output: https://cli.r-lib.org/reference/inline-markup.html#classes? I started in 2a7e4c4, would you like to pick it up if you think it's worth it?

**Comment by wlandau** [comment]
> There's also usethis:git_sitrep(), usethis:proj_sitrep() and cli::cli_sitrep() with similar purposes.

Fair enough, sounds like sitrep is standard.

> Can we use markup to highlight important information in the output:

Sure. Implemented in df1a83f81af20b67039a6372f37c5374ef027c1f.

**Comment by wlandau** [comment]
FYI: in cdb318f1c5f070951cc2f76dd91c8341734eb83d, I changed the names of the three `PROFFER_` environment variables to increase clarity and especially avoid confusion with `GOPATH`. Is that alright? The new names are `PROFFER_PPROF_BIN`, `PROFFER_GO_BIN`, and `PROFFER_GRAPHVIZ_BIN`.

**Review by krlmlr — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
